language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: gAgoge2cVz0BSq4Sh+ZYIvNOuDqHZR3H2r+CD8iT89GUVwo4U59DFXj+Bo8Z3It/evymbMIox+pmlANiP+5dyXEo7383kNTc6G4PeIcXC1n3W0IDYTicjKozwpceyIovLWTwEDlUinnLByg85rDFi6cY2qWXh9CeP5HCyfVTJyyQnwlBFCJuYY376LeXD1RoFoEEYsYXYgAxjGKHP3HvgSCqI6njhLBwvctYs515goBcZej7tVWu/TdVLjvTbAbrzrIu1sCc5Kci5fUJmqkOdueRS2VBjcytOdJbwu0AEiHCIBjYrhZ4zCL62+dswHERUr/rrImgMNRL56dfn1CSqcfEVS2dqxHyYjVmJHlRLrxxRqHH6cbZrEHxZ6DGkY5erNokiUk6U7FbMzefbNhU35luuQUa4DRA4Np95OMJlwlG77NhMHsI0RmgY953xvEU3RT4la/layEGH29c2FCe9FeL7I240mWjnQ2rDAE8d6DKNQnl2kiOpeT6nI/M5LkYxXtuXAAe6jRStWPZ7V7kgpzJavwakyaXkEard5OXXr6R4A1xtuiDMdULjUWoQDm+nx+vEPUfQKEG9nt1KUQNRrPmP/xeHCqqxoVpWuqqliLkINoqFc6xXMFd/AX1VveXGowm9FrkK6DRynRKgjur/mzAgMNTTA+Tyq9EiLVh2l0=
  app: secret-badlands-98715
  on:
    repo: jorgerodriguez434/node-shopping-list-integration-tests
